### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by tommiekn** [pvtl/voyager-frontend#72] opened 2020-05-03 15:17 UTC
Hi there,

I recently updated a project to laravel6 and latest version of voyager/frontend and having now a weird issue on the scheduler.

I get every day an error log for:
CommandNotFoundException
Command "voyager-frontend:clean-thumbnails" is not defined.

However i can execute the command manually with no issues so not sure what is this about.

Tried an artisan optimize but nothing changed. Any idea of what is generating this issue?

Thanks!

**Comment by Liam-PVTL** [comment] 2020-07-07 02:26
Hey @tommiekn, 

When you say you're having an issue on the scheduler - where are you running this from? 

I'll assume it's a scheduled command in the App\Console\Kernel.php file. I would suggest double checking for typos in this file - as you said, we can run it from the command line so it indicates there may be something else going on, rather than there being a bug with the command.

I did set up a similar file to attempt to recreate this: 

`$schedule->command('voyager-frontend:clear-thumbnails')->everyMinute();`

Which was running just fine.

Feel free to drop a comment here, but I'm closing this for now.

**Comment by tommiekn** [comment] 2020-07-07 08:17
Hi @Liam-PVTL ,

I am not running this command from my app, the command is declared in voyager-frontend and is added to the package provider "VoyagerFrontendServiceProvider.php":

`$schedule->command('voyager-frontend:clean-thumbnails')->dailyAt('13:00');`

I am getting an error in the logs everyday at 13 with a command not found exception but as mentioned i can run the command just fine from shell.
Is very odd, not sure whats the problem here, except for this my app doesnt have any error or issue and everything works fine, tried to delete any cache possible but no luck, ran a search for "clear-thumbnails" on all the project but only voyager-frontend declares it.

**Comment by Liam-PVTL** [comment] 2020-07-07 22:02
Thanks @tommiekn. I'll re-open this for further investigation.

**Comment by Liam-PVTL** [comment] 2020-08-10 00:54
Hey @tommiekn, I did manage to let it run just fine via the laravel scheduler. Can you provide any steps to reproduce this from a fresh install? Thanks

**Comment by Liam-PVTL** [comment] 2020-11-02 00:40
Closing due to inactivity.

**Closed by Liam-PVTL** 2020-11-02 00:40 UTC
Labels: awaiting response, bug
